import "./globals.css";
import Navbar from "./components/navbar";
import { Inter, Montserrat } from "next/font/google";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Navbar />
        <div className="pl-56 pt-16 min-h-screen bg-slate-200">
          {children}
        </div>

      </body>
    </html>
  );
}